sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login $server -u="$username" -p="$password"
      - docker build -t $tag .
      - docker images
      - docker tag $tag $username/$tag
      - docker push $username/$tag
    - stage: test
      script: docker run --rm $username/$tag
    - script: docker run --rm $username/$tag